name: localtesting

services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
  database:
    image: "postgres:16.1"
    container_name: "database"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=omgservers
      - POSTGRES_PASSWORD=omgservers
      - POSTGRES_DB=omgservers
    ports:
      - "5432:5432"
    networks:
      - omgservers
  broker:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "broker"
    restart: unless-stopped
    environment:
      - ARTEMIS_USER=omgservers
      - ARTEMIS_PASSWORD=omgservers
    ports:
      - "5672:5672"
      - "8161:8161"
    networks:
      - omgservers
    volumes:
      - ./broker_config.xml:/var/lib/artemis-instance/etc-override/broker.xml
      - ./broker_log4j2.properties:/var/lib/artemis-instance/etc-override/log4j2.properties
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    restart: unless-stopped
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
    ports:
      - "5000:5000"
    networks:
      - omgservers
    command: "/etc/docker/registry/registry_config.yaml"
  builder:
    image: "omgservers/builder:${OMGSERVERS_VERSION}"
    container_name: "builder"
    restart: unless-stopped
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://localhost:7070
      - JENKINS_ADMIN_ID=builder
      - JENKINS_ADMIN_PASSWORD=builder
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - OMGSERVERS_BUILDER_USERNAME=builder
      - OMGSERVERS_BUILDER_USER_PASSWORD=builder
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5000
networks:
  omgservers:
    name: omgservers