version: "3.8"
services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    ports:
      - "5050:5000"
    networks:
      - omgservers
  builder:
    image: "omgservers/omgservers-builder:1.0.0-SNAPSHOT"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://builder:8080
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5050
  service:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service"
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - omgservers
    depends_on:
      - database
      - queues
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DATABASE_URL=postgresql://database:5432/root
      - OMGSERVERS_QUEUES_HOST=queues
      - OMGSERVERS_INDEX_SERVER_URI=http://service:8080
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://service:8080
      - OMGSERVERS_BOOTSTRAP_ROOT_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_ADMIN_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_SUPPORT_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DOCKER_HOST_ENABLED=true
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  database:
    image: "postgres:15.1"
    container_name: "database"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=512
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  queues:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "queues"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers