version: "3.8"
services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc"
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - omgservers
    depends_on:
      - db
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_ROOT_LOG_LEVEL=INFO
      - OMGSERVERS_CONSOLE_LOG_ENABLED=true
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_TRAFFIC_LOG_LEVEL=INFO
      - OMGSERVERS_ACCESS_LOG_ENABLED=false
      - OMGSERVERS_DATASOURCE_URL=postgresql://db:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_MIGRATION_CONCURRENCY=1
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_HANDLER_COUNT=4
      - OMGSERVERS_HANDLER_LIMIT=2
      - OMGSERVERS_SCHEDULER_ENABLED=true
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=0
      - OMGSERVERS_EXTERNAL_URI=http://svc:8080
      - OMGSERVERS_INTERNAL_URI=http://svc:8080
      - OMGSERVERS_SERVICE_USERNAME=service
      - OMGSERVERS_SERVICE_PASSWORD=service
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD=admin
      - OMGSERVERS_ADDRESSES=http://svc:8080
      - OMGSERVERS_SHARD_COUNT=1
      - OMGSERVERS_BOOTSTRAP_SERVICE=true
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_INACTIVE_INTERVAL=10
      - OMGSERVERS_WORKERS_NETWORK=omgservers
      - OMGSERVERS_DISABLE_DOCKER=false
      - OMGSERVERS_DOCKER_HOST=tcp://docker:2375
  db:
    image: "postgres:15.1"
    container_name: "db"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=512
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers