version: "3.8"
services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc"
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - omgservers
    depends_on:
      - db
      - mq
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=mq
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_EXTERNAL_URI=http://svc:8080
      - OMGSERVERS_INTERNAL_URI=http://svc:8080
      - OMGSERVERS_ADDRESSES=http://svc:8080
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  db:
    image: "postgres:15.1"
    container_name: "db"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=512
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers