version: "3.8"
services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    volumes:
      - ./registry-certs:/certs
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
    ports:
      - "5050:5000"
    networks:
      - omgservers
  builder:
    image: "omgservers/omgservers-builder:1.0.0-SNAPSHOT"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://builder:8080
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5050
  gateway:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./envoy-gateway.yaml:/etc/envoy/envoy.yaml
  service-1:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "service-1"
    networks:
      - omgservers
    volumes:
      - ./envoy-service-1.yaml:/etc/envoy/envoy.yaml
  service-1-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-1-a"
    networks:
      - omgservers
    depends_on:
      - database-1
      - queues-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-1:5432/root
      - OMGSERVERS_MQ_HOST=queues-1
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-1:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://service-1:8080,http://service-2:8080,http://service-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-1:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=0
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  service-1-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-1-b"
    networks:
      - omgservers
    depends_on:
      - database-1
      - queues-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-1:5432/root
      - OMGSERVERS_MQ_HOST=queues-1
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-1:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-1:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=1
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  database-1:
    image: "postgres:16"
    container_name: "database-1"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  queues-1:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "queues-1"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  service-2:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "service-2"
    networks:
      - omgservers
    volumes:
      - ./envoy-service-2.yaml:/etc/envoy/envoy.yaml
  service-2-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-2-a"
    networks:
      - omgservers
    depends_on:
      - database-2
      - queues-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-2:5432/root
      - OMGSERVERS_MQ_HOST=queues-2
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-2:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://service-1:8080,http://service-2:8080,http://service-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-2:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=2
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  service-2-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-2-b"
    networks:
      - omgservers
    depends_on:
      - database-2
      - queues-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-2:5432/root
      - OMGSERVERS_MQ_HOST=queues-2
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-2:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-2:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=3
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  database-2:
    image: "postgres:16"
    container_name: "database-2"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  queues-2:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "queues-2"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  service-3:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "service-3"
    networks:
      - omgservers
    volumes:
      - ./envoy-service-3.yaml:/etc/envoy/envoy.yaml
  service-3-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-3-a"
    networks:
      - omgservers
    depends_on:
      - database-3
      - queues-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-3:5432/root
      - OMGSERVERS_MQ_HOST=queues-3
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-3:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://service-1:8080,http://service-2:8080,http://service-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-3:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=4
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  service-3-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "service-3-b"
    networks:
      - omgservers
    depends_on:
      - database-3
      - queues-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=INFO
      - OMGSERVERS_DB_URL=postgresql://database-3:5432/root
      - OMGSERVERS_MQ_HOST=queues-3
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://service-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service-3:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=5
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  database-3:
    image: "postgres:16"
    container_name: "database-3"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  queues-3:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "queues-3"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers
