version: "3.8"
services:
  gateway:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./envoy-gw.yaml:/etc/envoy/envoy.yaml
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc-1:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-1"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-1.yaml:/etc/envoy/envoy.yaml
  svc-1-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-1-a"
    networks:
      - omgservers
    depends_on:
      - db-1
      - mq-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-1:5432/root
      - OMGSERVERS_MQ_HOST=mq-1
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-1:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-1:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=0
  svc-1-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-1-b"
    networks:
      - omgservers
    depends_on:
      - db-1
      - mq-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-1:5432/root
      - OMGSERVERS_MQ_HOST=mq-1
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-1:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-1:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=1
  db-1:
    image: "postgres:15.1"
    container_name: "db-1"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-1:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-1"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  svc-2:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-2"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-2.yaml:/etc/envoy/envoy.yaml
  svc-2-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-2-a"
    networks:
      - omgservers
    depends_on:
      - db-2
      - mq-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-2:5432/root
      - OMGSERVERS_MQ_HOST=mq-2
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-2:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-2:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=2
  svc-2-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-2-b"
    networks:
      - omgservers
    depends_on:
      - db-2
      - mq-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-2:5432/root
      - OMGSERVERS_MQ_HOST=mq-2
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-2:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-2:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=3
  db-2:
    image: "postgres:15.1"
    container_name: "db-2"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-2:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-2"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  svc-3:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-3"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-3.yaml:/etc/envoy/envoy.yaml
  svc-3-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-3-a"
    networks:
      - omgservers
    depends_on:
      - db-3
      - mq-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-3:5432/root
      - OMGSERVERS_MQ_HOST=mq-3
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-3:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-3:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=4
  svc-3-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-3-b"
    networks:
      - omgservers
    depends_on:
      - db-3
      - mq-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=DEBUG
      - OMGSERVERS_DB_URL=postgresql://db-3:5432/root
      - OMGSERVERS_MQ_HOST=mq-3
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_INDEX_SERVER_URI=http://svc-3:8080
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_LOCAL_HOST_URI=tcp://docker:2375
      - OMGSERVERS_WORKERS_SERVICE_URI=http://svc-3:8080
      - OMGSERVERS_GENERATOR_DATACENTER_ID=0
      - OMGSERVERS_GENERATOR_INSTANCE_ID=5
  db-3:
    image: "postgres:15.1"
    container_name: "db-3"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-3:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-3"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers
