version: "3.8"
services:
  gw:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gw"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./envoy-gw.yaml:/etc/envoy/envoy.yaml
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc-1:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-1"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-1.yaml:/etc/envoy/envoy.yaml
  svc-1-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-1-a"
    networks:
      - omgservers
    depends_on:
      - db-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-1:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:0
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  svc-1-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-1-b"
    networks:
      - omgservers
    depends_on:
      - db-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-1:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:1
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=false
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  db-1:
    image: "postgres:15.1"
    container_name: "db-1"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  svc-2:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-2"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-2.yaml:/etc/envoy/envoy.yaml
  svc-2-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-2-a"
    networks:
      - omgservers
    depends_on:
      - db-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-2:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:2
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  svc-2-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-2-b"
    networks:
      - omgservers
    depends_on:
      - db-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-2:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:3
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=false
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  db-2:
    image: "postgres:15.1"
    container_name: "db-2"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  svc-3:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "svc-3"
    networks:
      - omgservers
    volumes:
      - ./envoy-svc-3.yaml:/etc/envoy/envoy.yaml
  svc-3-a:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-3-a"
    networks:
      - omgservers
    depends_on:
      - db-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-3:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:4
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  svc-3-b:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-3-b"
    networks:
      - omgservers
    depends_on:
      - db-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=DEBUG
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-3:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_EXTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_DATACENTER_ID:0
      - OMGSERVERS_NODE_ID:5
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=false
      - OMGSERVERS_WORKERS_NETWORK=omgservers
  db-3:
    image: "postgres:15.1"
    container_name: "db-3"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers
