version: "3.8"
services:
  gw:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gw"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc1:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-1"
    networks:
      - omgservers
    depends_on:
      - db-1
      - mq-1
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_ROOT_LOG_LEVEL=INFO
      - OMGSERVERS_CONSOLE_LOG_ENABLED=true
      - OMGSERVERS_APP_LOG_LEVEL=INFO
      - OMGSERVERS_TRAFFIC_LOG_LEVEL=INFO
      - OMGSERVERS_ACCESS_LOG_ENABLED=false
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-1:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=mq-1
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_MIGRATION_CONCURRENCY=1
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_DISABLE_RELAY=false
      - OMGSERVERS_SCHEDULER_ENABLED=true
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=0
      - OMGSERVERS_EXTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-1:8080
      - OMGSERVERS_SERVICE_USERNAME=service
      - OMGSERVERS_SERVICE_PASSWORD=service
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD=admin
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=true
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_INACTIVE_INTERVAL=10
      - OMGSERVERS_WORKERS_NETWORK=omgservers
      - OMGSERVERS_DISABLE_DOCKER=false
      - OMGSERVERS_DOCKER_HOST=tcp://docker:2375
  db-1:
    image: "postgres:15.1"
    container_name: "db-1"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-1:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-1"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  svc-2:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-2"
    networks:
      - omgservers
    depends_on:
      - db-2
      - mq-2
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_ROOT_LOG_LEVEL=INFO
      - OMGSERVERS_CONSOLE_LOG_ENABLED=true
      - OMGSERVERS_APP_LOG_LEVEL=INFO
      - OMGSERVERS_TRAFFIC_LOG_LEVEL=INFO
      - OMGSERVERS_ACCESS_LOG_ENABLED=false
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-2:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=mq-2
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_MIGRATION_CONCURRENCY=1
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_DISABLE_RELAY=false
      - OMGSERVERS_SCHEDULER_ENABLED=true
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=1
      - OMGSERVERS_EXTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-2:8080
      - OMGSERVERS_SERVICE_USERNAME=service
      - OMGSERVERS_SERVICE_PASSWORD=service
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD=admin
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=true
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_INACTIVE_INTERVAL=10
      - OMGSERVERS_WORKERS_NETWORK=omgservers
      - OMGSERVERS_DISABLE_DOCKER=false
      - OMGSERVERS_DOCKER_HOST=tcp://docker:2375
  db-2:
    image: "postgres:15.1"
    container_name: "db-2"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-2:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-2"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
  svc-3:
    image: "omgservers/omgservers-service:1.0.0-SNAPSHOT"
    container_name: "svc-3"
    networks:
      - omgservers
    depends_on:
      - db-3
      - mq-3
    tmpfs:
      - /var/log/omgservers
    environment:
      - OMGSERVERS_ROOT_LOG_LEVEL=INFO
      - OMGSERVERS_CONSOLE_LOG_ENABLED=true
      - OMGSERVERS_APP_LOG_LEVEL=INFO
      - OMGSERVERS_TRAFFIC_LOG_LEVEL=INFO
      - OMGSERVERS_ACCESS_LOG_ENABLED=false
      - OMGSERVERS_DATASOURCE_URL=postgresql://db-3:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=mq-3
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_MIGRATION_CONCURRENCY=1
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_DISABLE_RELAY=false
      - OMGSERVERS_SCHEDULER_ENABLED=true
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=2
      - OMGSERVERS_EXTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_INTERNAL_URI=http://svc-3:8080
      - OMGSERVERS_SERVICE_USERNAME=service
      - OMGSERVERS_SERVICE_PASSWORD=service
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD=admin
      - OMGSERVERS_ADDRESSES=http://svc-1:8080,http://svc-2:8080,http://svc-3:8080
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_BOOTSTRAP_SERVICE=true
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_INACTIVE_INTERVAL=10
      - OMGSERVERS_WORKERS_NETWORK=omgservers
      - OMGSERVERS_DISABLE_DOCKER=false
      - OMGSERVERS_DOCKER_HOST=tcp://docker:2375
  db-3:
    image: "postgres:15.1"
    container_name: "db-3"
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  mq-3:
    image: "apache/activemq-artemis:2.31.2-alpine"
    container_name: "mq-3"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    networks:
      - omgservers
networks:
  omgservers:
    name: omgservers
