FROM apache/activemq-artemis:2.33.0-alpine

COPY src/main/docker/broker.xml /var/lib/artemis-instance/etc-override/broker.xml
COPY src/main/docker/log4j2.properties /var/lib/artemis-instance/etc-override/log4j2.properties
