version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: ${OMGSERVERS_ENVIRONMENT}
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  token:
    issuer: omgservers
    service: registry
    realm: ${OMGSERVERS_SERVICE_URL}/omgservers/v1/entrypoint/registry/token
    rootcertbundle: /root/certs/bundle/cert.pem
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [ nosniff ]
notifications:
  events:
    includereferences: true
  endpoints:
    - name: omgservers
      disabled: false
      url: ${OMGSERVERS_SERVICE_URL}/omgservers/v1/entrypoint/registry/events
      headers:
        Content-Type: [ application/json ]
      timeout: 5s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
        actions:
          - pull
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3