version: '2'
services:
  app-1:
    image: "omgservers/omgservers-application:1.0.0-SNAPSHOT"
    container_name: "app-1"
    depends_on:
      - db-1
    ports:
      - "10001:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db-1:5432/root
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db-1:5432/root
      - OMGSERVERS_DATACENTER_ID=1
      - OMGSERVERS_NODE_ID=1
      - OMGSERVERS_SERVER_URI=http://app-1:8080
      - OMGSERVERS_SERVICE_USERNAME=app-1
      - OMGSERVERS_SERVICE_PASSWORD=pas-1
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_MIGRATION_CONCURRENCY=4
      - OMGSERVERS_TOKEN_LIFETIME=600
      - OMGSERVERS_DISABLE_DISPATCHER=false
      - OMGSERVERS_DISPATCHER_LIMIT=32
      - OMGSERVERS_POSTPONE_INTERVAL=60
      - OMGSERVERS_STANDALONE=false
      - OMGSERVERS_VERBOSE=true
  db-1:
    image: "postgres:15.1"
    container_name: "db-1"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  app-2:
    image: "omgservers/omgservers-application:1.0.0-SNAPSHOT"
    container_name: "app-2"
    depends_on:
      - db-2
    ports:
      - "10002:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db-2:5432/root
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db-2:5432/root
      - OMGSERVERS_DATACENTER_ID=1
      - OMGSERVERS_NODE_ID=2
      - OMGSERVERS_SERVER_URI=http://app-2:8080
      - OMGSERVERS_SERVICE_USERNAME=app-2
      - OMGSERVERS_SERVICE_PASSWORD=pas-2
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_MIGRATION_CONCURRENCY=4
      - OMGSERVERS_TOKEN_LIFETIME=600
      - OMGSERVERS_DISABLE_DISPATCHER=false
      - OMGSERVERS_DISPATCHER_LIMIT=32
      - OMGSERVERS_POSTPONE_INTERVAL=60
      - OMGSERVERS_STANDALONE=false
      - OMGSERVERS_VERBOSE=true
  db-2:
    image: "postgres:15.1"
    container_name: "db-2"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  app-3:
    image: "omgservers/omgservers-application:1.0.0-SNAPSHOT"
    container_name: "app-3"
    depends_on:
      - db-3
    ports:
      - "10003:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db-3:5432/root
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db-3:5432/root
      - OMGSERVERS_DATACENTER_ID=1
      - OMGSERVERS_NODE_ID=3
      - OMGSERVERS_SERVER_URI=http://app-3:8080
      - OMGSERVERS_SERVICE_USERNAME=app-3
      - OMGSERVERS_SERVICE_PASSWORD=pas-3
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_INDEX_NAME=main
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_DISABLE_MIGRATION=false
      - OMGSERVERS_MIGRATION_CONCURRENCY=4
      - OMGSERVERS_TOKEN_LIFETIME=600
      - OMGSERVERS_DISABLE_DISPATCHER=false
      - OMGSERVERS_DISPATCHER_LIMIT=32
      - OMGSERVERS_POSTPONE_INTERVAL=60
      - OMGSERVERS_STANDALONE=false
      - OMGSERVERS_VERBOSE=true
  db-3:
    image: "postgres:15.1"
    container_name: "db-3"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
