local omgplayer = require("omgservers.omgplayer")

local service_url = os.getenv("OMGSERVERS_URL") or "http://localhost:8080"
local tenant_id = os.getenv("OMGSERVERS_TENANT_ID")
local stage_id = os.getenv("OMGSERVERS_STAGE_ID")
local stage_secret = os.getenv("OMGSERVERS_STAGE_SECRET")

local function handle_event(self, event)
	print("[GAMECLIENT] Event was received, event=" .. json.encode(event))

	local event_qualifier = event.qualifier
	local event_body = event.body

	if event_qualifier == omgplayer.constants.INITIALIZED_EVENT_QUALIFIER then
		omgplayer:sign_up()

	elseif event_qualifier == omgplayer.constants.SIGNED_UP_EVENT_QUALIFIER then
		local user_id = event_body.user_id
		local password = event_body.password
		print("[GAMECLIENT] User was created, user_id=" .. user_id)
		
		omgplayer:sign_in(user_id, password)

		self.user_id = user_id
		self.password = password
		
	elseif event_qualifier == omgplayer.constants.SIGNED_IN_EVENT_QUALIFIER then
		local client_id = event_body.client_id
		print("[GAMECLIENT] Client was created, client_id=" .. client_id)

		self.client_id = client_id
		
	elseif event_qualifier == omgplayer.constants.GREETED_EVENT_QUALIFIER then
		local version_id = event_body.version_id
		local version_created = event_body.version_created
		print("[GAMECLIENT] Client was greeted, version_id=" .. version_id .. ", version_created=" .. version_created)
		
	elseif event_qualifier == omgplayer.constants.ASSSIGNED_EVENT_QUALIFIER then
		local runtime_qualifier = event_body.runtime_qualifier
		local runtime_id = event_body.runtime_id

		print("[GAMECLIENT] Client was assigned, runtime_qualifier=" .. runtime_qualifier .. ", runtime_id=" .. runtime_id)
		
	elseif event_qualifier == omgplayer.constants.MESSAGE_RECEIVED_EVENT_QUALIFIER then
		local message = event_body.message
		print("[GAMECLIENT] Message was received, message=" .. json.encode(message))

		omgplayer:send_message({
			text = "confirm_message",
		})

	elseif event_qualifier == omgplayer.constants.CONNECTION_UPGRADED_EVENT_QUALIFIER then
		print("[GAMECLIENT] Connection was upgraded")

		omgplayer:send_message({
			text = "hello_message",
		})
		
	elseif event_qualifier == omgplayer.constants.FAILED_EVENT_QUALIFIER then
		local reason = event_body.reason
		print("[GAMECLIENT] Client failed, reason=" .. reason)
	end
end

function init(self)
	omgplayer:init(service_url, tenant_id, stage_id, stage_secret, function(event) handle_event(self, event) end)
end

function update(self, dt)
	omgplayer:update(dt)
end
