local omgplayer = require("omgservers.omgplayer")

local service_url = os.getenv("OMGSERVERS_URL")
local tenant_id = os.getenv("OMGSERVERS_TENANT_ID")
local stage_id = os.getenv("OMGSERVERS_STAGE_ID")
local stage_secret = os.getenv("OMGSERVERS_STAGE_SECRET")

function init(self)
	omgplayer:init(service_url, tenant_id, stage_id, stage_secret, function(event)
		print("[GAME] Event was received")
		pprint(event)
	end)

	omgplayer:sign_up(function(user_id, password)
		print("[GAME] User was created, user_id=" .. user_id)

		omgplayer:sign_in(user_id, password, function(api_token, client_id)
			print("[GAME] Client was created, client_id=" .. client_id)
		end)
	end)
end

function update(self, dt)
	omgplayer:update(dt)
end
