local omgplayer = require("omgservers.omgplayer.omgplayer")

local service_url = os.getenv("OMGSERVERS_SERVICE_URL") or "http://localhost:8080"
local tenant_id = os.getenv("OMGSERVERS_TENANT_ID")
local stage_id = os.getenv("OMGSERVERS_STAGE_ID")
local secret = os.getenv("OMGSERVERS_SECRET")

local function handle_event(self, event)
	print(socket.gettime() .. " [GAMECLIENT] Event was received, event=" .. json.encode(event))

	local event_qualifier = event.qualifier
	local event_body = event.body

	if event_qualifier == omgplayer.constants.INITIALIZED then
		omgplayer:sign_up()

	elseif event_qualifier == omgplayer.constants.SIGNED_UP then
		local user_id = event_body.user_id
		local password = event_body.password
		print(socket.gettime() .. " [GAMECLIENT] User was created, user_id=" .. user_id)
		
		omgplayer:sign_in(user_id, password)

		self.user_id = user_id
		self.password = password
		
	elseif event_qualifier == omgplayer.constants.SIGNED_IN then
		local client_id = event_body.client_id
		print(socket.gettime() .. " [GAMECLIENT] Client was created, client_id=" .. client_id)

		self.client_id = client_id
		
	elseif event_qualifier == omgplayer.constants.GREETED then
		local tenant_version_id = event_body.tenant_version_id
		local tenant_version_created = event_body.tenant_version_created
		print(socket.gettime() .. " [GAMECLIENT] Client was greeted, tenant_version_id=" .. tenant_version_id .. ", tenant_version_created=" .. tenant_version_created)
		
	elseif event_qualifier == omgplayer.constants.ASSIGNED then
		local runtime_qualifier = event_body.runtime_qualifier
		local runtime_id = event_body.runtime_id

		print(socket.gettime() .. " [GAMECLIENT] Client was assigned, runtime_qualifier=" .. runtime_qualifier .. ", runtime_id=" .. runtime_id)
		
	elseif event_qualifier == omgplayer.constants.MESSAGE_RECEIVED then
		local message = event_body.message
		print(socket.gettime() .. " [GAMECLIENT] Message was received, message=" .. message)

		omgplayer:send_text_message(json.encode({
			text = "confirm_message",
		}))

	elseif event_qualifier == omgplayer.constants.CONNECTION_UPGRADED then
		print(socket.gettime() .. " [GAMECLIENT] Connection was upgraded")

		omgplayer:send_text_message(json.encode({
			text = "hello_message",
		}))
		
	elseif event_qualifier == omgplayer.constants.PLAYER_FAILED then
		local reason = event_body.reason
		print(socket.gettime() .. " [GAMECLIENT] Client failed, reason=" .. reason)
	end
end

function init(self)
	local options = {
		service_url = service_url,
		tenant_id = tenant_id, 
		stage_id = stage_id, 
		stage_secret = secret, 
		event_handler = function(event) handle_event(self, event) end, 
		debug_logging = true,
	}
	omgplayer:init(options)
end

function update(self, dt)
	omgplayer:update(dt)
end
