version: "3.8"
services:
  docker:
    image: "docker:dind"
    container_name: "docker"
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - ~/.docker/certs:/certs/client
      - builder-data:/var/jenkins_home
    networks:
      - omgservers
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    command: [ "--insecure-registry=registry:5000" ]
  database:
    image: "postgres:15.1"
    container_name: "database"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=512
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    networks:
      - omgservers
  queues:
    image: "apache/activemq-artemis:2.33.0-alpine"
    container_name: "queues"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - ./broker.xml:/var/lib/artemis-instance/etc-override/broker.xml
    ports:
      - "5672:5672"
    networks:
      - omgservers
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    ports:
      - "5050:5000"
    networks:
      - omgservers
  builder:
    image: "omgservers/omgservers-builder:1.0.0-SNAPSHOT"
    container_name: "builder"
    ports:
      - "7070:8080"
      - "50000:50000"
    volumes:
      - ~/.docker/certs:/certs/client:ro
      - builder-data:/var/jenkins_home
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://localhost:7070
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_REGISTRY=http://registry:5000
volumes:
  builder-data:
networks:
  omgservers:
    name: omgservers