name: omgservers

services:
  docker:
    image: "alpine/socat"
    container_name: "docker"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: "postgres:16.1"
    container_name: "database"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "omgservers"
      POSTGRES_PASSWORD: "omgservers"
      POSTGRES_DB: "omgservers"
      PAGER: "cat"
    ports:
      - "5432:5432"
    networks:
      - omgservers
  cache:
    image: redis:7
    container_name: "cache"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - omgservers
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    command: "/etc/docker/registry/registry_config.yaml"
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - omgservers
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
  service:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service"
    restart: unless-stopped
    depends_on:
      - docker
      - database
      - cache
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database:5432/omgservers
      - OMGSERVERS_DATABASE_PASSWORD=omgservers
      - OMGSERVERS_CACHE_HOSTS=redis://cache:6379
      - OMGSERVERS_USER_PASSWORD=service
      - OMGSERVERS_INDEX_SHARDS_0_=http://localhost:8080
      - OMGSERVERS_SLOTS_COUNT=1
      - OMGSERVERS_MASTER_URI=http://localhost:8080
      - OMGSERVERS_SHARD_ID=0
      - OMGSERVERS_SHARD_URI=http://localhost:8080
      - OMGSERVERS_CLIENT_CONNECTOR_URI=ws://localhost:8081
      - OMGSERVERS_CLIENT_DISPATCHER_URI=ws://localhost:8082
      - OMGSERVERS_RUNTIME_SERVICE_URI=http://service:8080
      - OMGSERVERS_RUNTIME_DISPATCHER_URI=ws://dispatcher:8080
      - OMGSERVERS_REGISTRY_URI=http://localhost:5000
      - OMGSERVERS_BOOTSTRAP_ADMIN_USER_PASSWORD=admin
      - OMGSERVERS_BOOTSTRAP_SUPPORT_USER_PASSWORD=support
      - OMGSERVERS_BOOTSTRAP_SERVICE_USER_PASSWORD=service
      - OMGSERVERS_BOOTSTRAP_CONNECTOR_USER_PASSWORD=connector
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__SERVER_URI=localhost
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MAX_CONTAINERS=16
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./jwt_private_key.pem:/jwt_issuer/private_key.pem:ro
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
      - ./jwt_issuer_cert.pem:/jwt_issuer/cert.pem:ro
  connector:
    image: "omgservers/connector:${OMGSERVERS_VERSION}"
    container_name: "connector"
    restart: unless-stopped
    environment:
      OMGSERVERS_APP_LOG_LEVEL: "${CONNECTOR_LOG_LEVEL}"
      OMGSERVERS_SERVICE_URI: "http://service:8080"
      OMGSERVERS_USER_PASSWORD: "connector"
    ports:
      - "8081:8080"
    networks:
      - omgservers
    volumes:
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
  dispatcher:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher"
    restart: unless-stopped
    environment:
      OMGSERVERS_APP_LOG_LEVEL: "${DISPATCHER_LOG_LEVEL}"
    ports:
      - "8082:8080"
    networks:
      - omgservers
    volumes:
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
networks:
  omgservers:
    name: omgservers
