#!/bin/bash
set -e

# HELP

help() {
  echo "OMGSERVERS ctl, v1.0.0"
  echo "Usage:"
  if [ -z "$1" -o "$1" = "help" ]; then
    echo " omgserversctl help"
  fi
  if [ -z "$1" -o "$1" = "logs" ]; then
    echo " omgserversctl logs"
  fi
  # Environment
  if [ -z "$1" -o "$1" = "environment" -o "$1" = "environment printCurrent" ]; then
    echo " omgserversctl environment printCurrent"
  fi
  if [ -z "$1" -o "$1" = "environment" -o "$1" = "environment useEnvironment" ]; then
    echo " omgserversctl environment useEnvironment <name> <external_url> <internal_url>"
  fi
  # Admin
  if [ -z "$1" -o "$1" = "admin" -o "$1" = "admin useCredentials" ]; then
    echo " omgserversctl admin useCredentials <user_id> <password>"
  fi
  if [ -z "$1" -o "$1" = "admin" -o "$1" = "admin printCurrent" ]; then
    echo " omgserversctl admin printCurrent"
  fi
  if [ -z "$1" -o "$1" = "admin" -o "$1" = "admin createToken" ]; then
    echo " omgserversctl admin createToken"
  fi
  # Support
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support useCredentials" ]; then
    echo " omgserversctl support useCredentials <user_id> <password>"
  fi
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support printCurrent" ]; then
    echo " omgserversctl support printCurrent"
  fi
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support createToken" ]; then
    echo " omgserversctl support createToken"
  fi
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support createTenant" ]; then
    echo " omgserversctl support createTenant"
  fi
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support deleteTenant" ]; then
    echo " omgserversctl support deleteTenant"
  fi
  if [ -z "$1" -o "$1" = "support" -o "$1" = "support createDeveloper" ]; then
    echo " omgserversctl support createDeveloper"
  fi
  # Developer
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useCredentials" ]; then
    echo " omgserversctl developer useCredentials <user_id> <password>"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printCurrent" ]; then
    echo " omgserversctl developer printCurrent"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer createToken" ]; then
    echo " omgserversctl developer createToken"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useTenant" ]; then
    echo " omgserversctl developer useTenant <tenant_id>"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printTenant" ]; then
    echo " omgserversctl developer printTenant"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer createProject" ]; then
    echo " omgserversctl developer createProject"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useProject" ]; then
    echo " omgserversctl developer useProject <project_id>"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printProject" ]; then
    echo " omgserversctl developer printProject"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useStage" ]; then
    echo " omgserversctl developer useStage <stage_id>"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printStage" ]; then
    echo " omgserversctl developer printStage"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer getTenantDashboard" ]; then
    echo " omgserversctl developer getTenantDashboard"
  fi
  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer uploadVersion" ]; then
    echo " omgserversctl developer uploadVersion <project_path>"
  fi
}

logs() {
  cat ~/.omgservers/logs
}

# ENVIRONMENT

environment_printCurrent() {
  env | grep OMGSERVERSCTL_ | sort
}

environment_useEnvironment() {
  ENVIRONMENT_NAME=$1
  ENVIRONMENT_EXTERNAL_URL=$2
  ENVIRONMENT_INTERNAL_URL=$3

  if [ -z "${ENVIRONMENT_NAME}" -o -z "${ENVIRONMENT_EXTERNAL_URL}" -o -z "${ENVIRONMENT_INTERNAL_URL}" ]; then
    help "environment useEnvironment"
    exit 1
  fi

  : > ~/.omgservers/environment

  echo "export OMGSERVERSCTL_ENVIRONMENT_NAME=${ENVIRONMENT_NAME}" >> ~/.omgservers/environment
  echo "export OMGSERVERSCTL_ENVIRONMENT_EXTERNAL_URL=${ENVIRONMENT_EXTERNAL_URL}" >> ~/.omgservers/environment
  echo "export OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL=${ENVIRONMENT_INTERNAL_URL}" >> ~/.omgservers/environment

  echo "$(date) $(echo $ENVIRONMENT_NAME) Environment was set, NAME=${ENVIRONMENT_NAME}, EXTERNAL_URL=${ENVIRONMENT_EXTERNAL_URL}, INTERNAL_URL=${ENVIRONMENT_INTERNAL_URL}"
}

# ADMIN

admin_useCredentials() {
  internal_useEnvironment

  ADMIN_USER_ID=$1
  ADMIN_PASSWORD=$2

  if [ -z "${ADMIN_USER_ID}" -o -z "${ADMIN_PASSWORD}" ]; then
    help "admin useCredentials"
    exit 1
  fi

  echo "export OMGSERVERSCTL_ADMIN_USER_ID=${ADMIN_USER_ID}" >> ~/.omgservers/environment
  echo "export OMGSERVERSCTL_ADMIN_PASSWORD=${ADMIN_PASSWORD}" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Admin credentials were set, ADMIN_USER_ID=${ADMIN_USER_ID}"

  internal_useEnvironment
  admin_createToken
}

admin_printCurrent() {
  internal_useEnvironment

  ADMIN_USER_ID=${OMGSERVERSCTL_ADMIN_USER_ID}
  ADMIN_USER_PASSWORD=${OMGSERVERSCTL_ADMIN_PASSWORD}
  ADMIN_TOKEN=${OMGSERVERSCTL_ADMIN_TOKEN}

  if [ -z "${ADMIN_USER_ID}" -o -z "${ADMIN_USER_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current admin was not set"
    exit 1
  fi

  if [ -z "${ADMIN_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current admin was found, ADMIN_USER_ID=${ADMIN_USER_ID}, (without token)"
  else
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current admin was found, ADMIN_USER_ID=${ADMIN_USER_ID}, (token exists)"
  fi
}

admin_createToken() {
  internal_useEnvironment

  ADMIN_USER_ID=${OMGSERVERSCTL_ADMIN_USER_ID}
  ADMIN_PASSWORD=${OMGSERVERSCTL_ADMIN_PASSWORD}

  if [ -z "${ADMIN_USER_ID}" -o -z "${ADMIN_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current admin credentials were not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using admin, USER_ID=${ADMIN_USER_ID}"

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL}/omgservers/v1/entrypoint/admin/request/create-token"
  REQUEST="{\"user_id\": \"${ADMIN_USER_ID}\", \"password\": \"${ADMIN_PASSWORD}\"}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/admin-create-token_${ADMIN_USER_ID}.json)

  cat ~/.omgservers/temp/admin-create-token_${ADMIN_USER_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  ADMIN_TOKEN=$(cat ~/.omgservers/temp/admin-create-token_${ADMIN_USER_ID}.json | jq -r .raw_token)
  if [ -z "$ADMIN_TOKEN" -o "$ADMIN_TOKEN" == "null" ]; then
    echo "ERROR: ADMIN_TOKEN was not received"
    exit 1
  fi

  echo "export OMGSERVERSCTL_ADMIN_TOKEN=$ADMIN_TOKEN" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Admin token was created"

}

# SUPPORT

support_useCredentials() {
  internal_useEnvironment

  SUPPORT_USER_ID=$1
  SUPPORT_PASSWORD=$2

  if [ -z "${SUPPORT_USER_ID}" -o -z "${SUPPORT_PASSWORD}" ]; then
    help "support useCredentials"
    exit 1
  fi

  echo "export OMGSERVERSCTL_SUPPORT_USER_ID=$SUPPORT_USER_ID" >> ~/.omgservers/environment
  echo "export OMGSERVERSCTL_SUPPORT_USER_PASSWORD=$SUPPORT_PASSWORD" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Support credentials were set, SUPPORT_USER_ID=$SUPPORT_USER_ID"

  internal_useEnvironment
  support_createToken

}

support_printCurrent() {
  internal_useEnvironment

  SUPPORT_USER_ID=${OMGSERVERSCTL_SUPPORT_USER_ID}
  SUPPORT_USER_PASSWORD=${OMGSERVERSCTL_SUPPORT_USER_PASSWORD}
  SUPPORT_TOKEN=${OMGSERVERSCTL_SUPPORT_TOKEN}

  if [ -z "${SUPPORT_USER_ID}" -o -z "${SUPPORT_USER_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current support was not found"
    exit 1
  fi

  if [ -z "${SUPPORT_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current support was found, SUPPORT_USER_ID=$SUPPORT_USER_ID, (without token)"
  else
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current support was found, SUPPORT_USER_ID=$SUPPORT_USER_ID, (token exists)"
  fi
}

support_createToken() {
  internal_useEnvironment

  SUPPORT_USER_ID=$OMGSERVERSCTL_SUPPORT_USER_ID
  SUPPORT_PASSWORD=$OMGSERVERSCTL_SUPPORT_USER_PASSWORD

  if [ -z "${SUPPORT_USER_ID}" -o -z "${SUPPORT_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current support credentials were not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using support, USER_ID=$SUPPORT_USER_ID"

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL}/omgservers/v1/entrypoint/support/request/create-token"
  REQUEST="{\"user_id\": \"${SUPPORT_USER_ID}\", \"password\": \"${SUPPORT_PASSWORD}\"}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/support-create-token_${SUPPORT_USER_ID}.json)

  cat ~/.omgservers/temp/support-create-token_${SUPPORT_USER_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  RAW_TOKEN=$(cat ~/.omgservers/temp/support-create-token_${SUPPORT_USER_ID}.json | jq -r .raw_token)
  if [ -z "$RAW_TOKEN" -o "$RAW_TOKEN" == "null" ]; then
    echo "ERROR: RAW_TOKEN was not received"
    exit 1
  fi

  echo "export OMGSERVERSCTL_SUPPORT_TOKEN=$RAW_TOKEN" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Support token was created"
}

support_createTenant() {
  internal_useEnvironment

  SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN

  if [ -z "${SUPPORT_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current support token was not found"
    exit 1
  fi

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL}/omgservers/v1/entrypoint/support/request/create-tenant"
  REQUEST="{}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer ${SUPPORT_TOKEN}" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/support-create-tenant.json)

  cat ~/.omgservers/temp/support-create-tenant.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  TENANT_ID=$(cat ~/.omgservers/temp/support-create-tenant.json | jq -r .id)
  if [ -z "$TENANT_ID" -o "$TENANT_ID" == "null" ]; then
    echo "ERROR: TENANT_ID was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_TENANT_ID=$TENANT_ID" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Tenant was created, TENANT_ID=$TENANT_ID"
}

support_deleteTenant() {
  internal_useEnvironment

  SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN

  if [ -z "${SUPPORT_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current support token was not found"
    exit 1
  fi

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL}/omgservers/v1/entrypoint/support/request/delete-tenant"
  REQUEST="{\"tenant_id\": \"${TENANT_ID}\"}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer ${SUPPORT_TOKEN}" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/support-delete-tenant_${TENANT_ID}.json)

  cat ~/.omgservers/temp/support-delete-tenant_${TENANT_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  DELETED=$(cat ~/.omgservers/temp/support-delete-tenant_${TENANT_ID}.json | jq -r .deleted)
  if [ -z "$DELETED" -o "$DELETED" == "null" ]; then
    echo "ERROR: DELETED was not received"
    exit 1
  fi

  if [ "${DELETED}" == "true" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Tenant was deleted, TENANT_ID=${TENANT_ID}"
  else
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Tenant was not deleted, TENANT_ID=${TENANT_ID}"
  fi
}

support_createDeveloper() {
  internal_useEnvironment

  SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN

  if [ -z "${SUPPORT_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current support token was not found"
    exit 1
  fi

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using tenant, TENANT_ID=$TENANT_ID"

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_INTERNAL_URL}/omgservers/v1/entrypoint/support/request/create-developer"
  REQUEST="{\"tenant_id\": ${TENANT_ID}}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer ${SUPPORT_TOKEN}" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/support-create-developer_${TENANT_ID}.json)

  cat ~/.omgservers/temp/support-create-developer_${TENANT_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  USER_ID=$(cat ~/.omgservers/temp/support-create-developer_${TENANT_ID}.json | jq -r .user_id)
  if [ -z "$USER_ID" -o "$USER_ID" == "null" ]; then
    echo "ERROR: USER_ID was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_DEVELOPER_USER_ID=$USER_ID" >> ~/.omgservers/environment

  PASSWORD=$(cat ~/.omgservers/temp/support-create-developer_${TENANT_ID}.json | jq -r .password)
  if [ -z "$PASSWORD" -o "$PASSWORD" == "null" ]; then
    echo "ERROR: PASSWORD was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_DEVELOPER_USER_PASSWORD=$PASSWORD" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Developer was created, USER_ID=$USER_ID"

  internal_useEnvironment
  developer_createToken
}

# DEVELOPER

developer_printCurrent() {
  internal_useEnvironment

  DEVELOPER_USER_ID=${OMGSERVERSCTL_DEVELOPER_USER_ID}
  DEVELOPER_PASSWORD=${OMGSERVERSCTL_DEVELOPER_USER_PASSWORD}
  DEVELOPER_TOKEN=${OMGSERVERSCTL_DEVELOPER_TOKEN}

  if [ -z "${DEVELOPER_USER_ID}" -o -z "${DEVELOPER_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current developer was not found"
    exit 1
  fi

  if [ -z "${DEVELOPER_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current developer was found, DEVELOPER_USER_ID=${DEVELOPER_USER_ID}, (without token)"
  else
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Current developer was found, DEVELOPER_USER_ID=${DEVELOPER_USER_ID}, (token exists)"
  fi
}

developer_createToken() {
  internal_useEnvironment

  DEVELOPER_USER_ID=$OMGSERVERSCTL_DEVELOPER_USER_ID
  DEVELOPER_PASSWORD=$OMGSERVERSCTL_DEVELOPER_USER_PASSWORD

  if [ -z "${DEVELOPER_USER_ID}" -o -z "${DEVELOPER_PASSWORD}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current developer credentials were not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using developer, USER_ID=$DEVELOPER_USER_ID"

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_EXTERNAL_URL}/omgservers/v1/entrypoint/developer/request/create-token"
  REQUEST="{\"user_id\": \"${DEVELOPER_USER_ID}\", \"password\": \"${DEVELOPER_PASSWORD}\"}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/developer-create-token_${DEVELOPER_USER_ID}.json)

  cat ~/.omgservers/temp/developer-create-token_${DEVELOPER_USER_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  RAW_TOKEN=$(cat ~/.omgservers/temp/developer-create-token_${DEVELOPER_USER_ID}.json | jq -r .raw_token)
  if [ -z "$RAW_TOKEN" -o "$RAW_TOKEN" == "null" ]; then
    echo "ERROR: RAW_TOKEN was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_DEVELOPER_TOKEN=$RAW_TOKEN" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Developer token was created"
}

developer_useCredentials() {
  internal_useEnvironment

  DEVELOPER_USER_ID=$1
  DEVELOPER_PASSWORD=$2

  if [ -z "${DEVELOPER_USER_ID}" -o -z "${DEVELOPER_PASSWORD}" ]; then
    help "developer useCredentials"
    exit 1
  fi

  echo "export OMGSERVERSCTL_DEVELOPER_USER_ID=$DEVELOPER_USER_ID" >> ~/.omgservers/environment
  echo "export OMGSERVERSCTL_DEVELOPER_USER_PASSWORD=$DEVELOPER_PASSWORD" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Developer credentials were set, DEVELOPER_USER_ID=$DEVELOPER_USER_ID"

  internal_useEnvironment
  developer_createToken
}

developer_useTenant() {
  internal_useEnvironment

  TENANT_ID=$1

  if [ -z "${TENANT_ID}" ]; then
    help "developer useTenant"
    exit 1
  fi

  echo "export OMGSERVERSCTL_TENANT_ID=${TENANT_ID}" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Tenant was set, TENANT_ID=$TENANT_ID"
}

developer_printTenant() {
  internal_useEnvironment

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Tenant was found, TENANT_ID=${TENANT_ID}"
}

developer_createProject() {
  internal_useEnvironment

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using tenant, TENANT_ID=$TENANT_ID"

  DEVELOPER_TOKEN=$OMGSERVERSCTL_DEVELOPER_TOKEN

  if [ -z "${DEVELOPER_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current developer token was not found"
    exit 1
  fi

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_EXTERNAL_URL}/omgservers/v1/entrypoint/developer/request/create-project"
  REQUEST="{\"tenant_id\": ${TENANT_ID}}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer ${DEVELOPER_TOKEN}" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/developer-create-project_${TENANT_ID}.json)

  cat ~/.omgservers/temp/developer-create-project_${TENANT_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  PROJECT_ID=$(cat ~/.omgservers/temp/developer-create-project_${TENANT_ID}.json | jq -r .project_id)
  if [ -z "$PROJECT_ID" -o "$PROJECT_ID" == "null" ]; then
    echo "ERROR: PROJECT_ID was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_PROJECT_ID=$PROJECT_ID" >> ~/.omgservers/environment

  STAGE_ID=$(cat ~/.omgservers/temp/developer-create-project_${TENANT_ID}.json | jq -r .stage_id)
  if [ -z "$STAGE_ID" -o "$STAGE_ID" == "null" ]; then
    echo "ERROR: STAGE_ID was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_STAGE_ID=$STAGE_ID" >> ~/.omgservers/environment

  STAGE_SECRET=$(cat ~/.omgservers/temp/developer-create-project_${TENANT_ID}.json | jq -r .secret)
  if [ -z "$STAGE_SECRET" -o "$STAGE_SECRET" == "null" ]; then
    echo "ERROR: STAGE_SECRET was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_STAGE_SECRET=$STAGE_SECRET" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Project was created, PROJECT_ID=$PROJECT_ID, STAGE_ID=$STAGE_ID"
}

developer_getTenantDashboard() {
  internal_useEnvironment

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using tenant, TENANT_ID=$TENANT_ID"

  DEVELOPER_TOKEN=$OMGSERVERSCTL_DEVELOPER_TOKEN

  if [ -z "${DEVELOPER_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current developer token was not found"
    exit 1
  fi

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_EXTERNAL_URL}/omgservers/v1/entrypoint/developer/request/get-tenant-dashboard"
  REQUEST="{\"tenant_id\": ${TENANT_ID}}"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs
  echo $REQUEST >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: application/json" \
    -H "Authorization: Bearer ${DEVELOPER_TOKEN}" \
    -d "${REQUEST}" \
    -o ~/.omgservers/temp/developer-get-tenant-dashboard_${TENANT_ID}.json)

  cat ~/.omgservers/temp/developer-get-tenant-dashboard_${TENANT_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  open ~/.omgservers/temp/developer-get-tenant-dashboard_${TENANT_ID}.json
}

developer_useProject() {
  internal_useEnvironment

  PROJECT_ID=$1

  if [ -z "${PROJECT_ID}" ]; then
    help "developer useProject"
    exit 1
  fi

  echo "export OMGSERVERSCTL_PROJECT_ID=${PROJECT_ID}" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Project was set, PROJECT_ID=$PROJECT_ID"
}

developer_printProject() {
  internal_useEnvironment

  PROJECT_ID=$OMGSERVERSCTL_PROJECT_ID

  if [ -z "${PROJECT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current project was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Project was found, PROJECT_ID=${PROJECT_ID}"
}

developer_useStage() {
  internal_useEnvironment

  STAGE_ID=$1

  if [ -z "${STAGE_ID}" ]; then
    help "developer useStage"
    exit 1
  fi

  echo "export OMGSERVERSCTL_STAGE_ID=${STAGE_ID}" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Stage was set, STAGE_ID=$STAGE_ID"
}

developer_printStage() {
  internal_useEnvironment

  STAGE_ID=$OMGSERVERSCTL_STAGE_ID

  if [ -z "${STAGE_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current stage was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Stage was found, STAGE_ID=${STAGE_ID}"
}

developer_uploadVersion() {
  internal_useEnvironment

  PROJECT_PATH=$1

  if [ -z "${PROJECT_PATH}" ]; then
    help "developer uploadVersion"
    exit 1
  fi

  TENANT_ID=$OMGSERVERSCTL_TENANT_ID

  if [ -z "${TENANT_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current tenant was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using tenant, TENANT_ID=$TENANT_ID"

  STAGE_ID=$OMGSERVERSCTL_STAGE_ID

  if [ -z "${STAGE_ID}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current stage was not found"
    exit 1
  fi

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Using stage, STAGE_ID=$STAGE_ID"

  DEVELOPER_TOKEN=$OMGSERVERSCTL_DEVELOPER_TOKEN

  if [ -z "${DEVELOPER_TOKEN}" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current developer token was not found"
    exit 1
  fi

  pushd ${PROJECT_PATH} >> /dev/null

  if [ ! -f "config.json" ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Version config.json was not found, PROJECT_PATH=${PROJECT_PATH}"
    exit 1
  fi

  mkdir -p .omgservers
  find . -type f -name "*.lua" | zip -@ .omgservers/project.zip

  ENDPOINT="${OMGSERVERSCTL_ENVIRONMENT_EXTERNAL_URL}/omgservers/v1/entrypoint/developer/request/upload-version"

  echo >> ~/.omgservers/logs
  echo $ENDPOINT >> ~/.omgservers/logs

  HTTP_CODE=$(curl -s -S -X PUT -w "%{http_code}" \
    "${ENDPOINT}" \
    -H "Content-type: multipart/form-data" \
    -H "Authorization: Bearer ${DEVELOPER_TOKEN}" \
    -F "tenantId=${TENANT_ID}" \
    -F "stageId=${STAGE_ID}" \
    -F "config.json=@./config.json" \
    -F "project.zip=@./.omgservers/project.zip" \
    -o ~/.omgservers/temp/developer-upload-version_${TENANT_ID}_${STAGE_ID}.json)

  cat ~/.omgservers/temp/developer-upload-version_${TENANT_ID}_${STAGE_ID}.json >> ~/.omgservers/logs
  echo >> ~/.omgservers/logs

  if [ "${HTTP_CODE}" -ge 400 ]; then
    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Operation was failed, HTTP_CODE=${HTTP_CODE}, ${ENDPOINT}"
    tail -2 ~/.omgservers/logs
    exit 1
  fi

  popd >> /dev/null

  VERSION_ID=$(cat ~/.omgservers/temp/developer-upload-version_${TENANT_ID}_${STAGE_ID}.json | jq -r .id)
  if [ -z "$VERSION_ID" -o "$VERSION_ID" == "null" ]; then
    echo "ERROR: VERSION_ID was not received"
    exit 1
  fi
  echo "export OMGSERVERSCTL_VERSION_ID=$VERSION_ID" >> ~/.omgservers/environment

  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Version was uploaded, VERSION_ID=${VERSION_ID}, TENANT_ID=${TENANT_ID}, STAGE_ID=${STAGE_ID}"
}

# INTERNAL

internal_useEnvironment() {
  source ~/.omgservers/environment

  if [ -z "${OMGSERVERSCTL_ENVIRONMENT_NAME}" ]; then
    echo "$(date) $(echo unknown) ERROR: Environment was not configured"
    help "environment useEnvironment"
    exit 1
  else
    source ~/.omgservers/environment
  fi
}

# MAIN

if [ ! -d "~/.omgservers/temp" ]; then
  mkdir -p ~/.omgservers/temp
fi
if [ ! -f "~/.omgservers/environment" ]; then
  touch ~/.omgservers/environment
fi
if [ ! -f "~/.omgservers/logs" ]; then
  touch ~/.omgservers/logs
fi

if [ -z "$1" -o "$1" = "help" ]; then
  help
  exit 0
fi

if [ -z "$1" -o "$1" = "logs" ]; then
  logs
  exit 0
fi

# Env
if [ "$1" = "environment" ]; then
  if [ "$2" = "printCurrent" ]; then
    environment_printCurrent
  elif [ "$2" = "useEnvironment" ]; then
    environment_useEnvironment $3 $4 $5
  else
    help "environment"
  fi
  exit 0
fi

# Admin
if [ "$1" = "admin" ]; then
  if [ "$2" = "useCredentials" ]; then
    admin_useCredentials $3 $4
  elif [ "$2" = "printCurrent" ]; then
    admin_printCurrent
  elif [ "$2" = "createToken" ]; then
    admin_createToken
  else
    help "admin"
  fi
# Support
elif [ "$1" = "support" ]; then
  if [ "$2" = "useCredentials" ]; then
    support_useCredentials $3 $4
  elif [ "$2" = "printCurrent" ]; then
    support_printCurrent
  elif [ "$2" = "createToken" ]; then
    support_createToken
  elif [ "$2" = "createTenant" ]; then
    support_createTenant
  elif [ "$2" = "deleteTenant" ]; then
    support_deleteTenant
  elif [ "$2" = "createDeveloper" ]; then
    support_createDeveloper $3
  else
    help "support"
  fi
# Developer
elif [ "$1" = "developer" ]; then
  if [ "$2" = "useCredentials" ]; then
    developer_useCredentials $3 $4
  elif [ "$2" = "printCurrent" ]; then
      developer_printCurrent
  elif [ "$2" = "createToken" ]; then
    developer_createToken
  elif [ "$2" = "useTenant" ]; then
    developer_useTenant $3
  elif [ "$2" = "printTenant" ]; then
      developer_printTenant
  elif [ "$2" = "createProject" ]; then
    developer_createProject
  elif [ "$2" = "useProject" ]; then
    developer_useProject $3
  elif [ "$2" = "printProject" ]; then
      developer_printProject
  elif [ "$2" = "useStage" ]; then
    developer_useStage $3
  elif [ "$2" = "printStage" ]; then
      developer_printStage
  elif [ "$2" = "getTenantDashboard" ]; then
    developer_getTenantDashboard
  elif [ "$2" = "uploadVersion" ]; then
    developer_uploadVersion $3
  else
    help "developer"
  fi
else
  help
fi
