name: development

services:
  ingress:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./gateway_config.yaml:/etc/envoy/gateway_config.yaml:ro
    command: "-c /etc/envoy/gateway_config.yaml"
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
  database:
    image: "postgres:16.1"
    container_name: "database"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  broker:
    image: "omgservers/broker:${OMGSERVERS_VERSION}"
    container_name: "broker"
    environment:
      - ARTEMIS_USER=broker
      - ARTEMIS_PASSWORD=broker
    ports:
      - "8161:8161"
    networks:
      - omgservers
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
    ports:
      - "5000:5000"
    networks:
      - omgservers
    command: "/etc/docker/registry/registry_config.yaml"
  builder:
    image: "omgservers/builder:${OMGSERVERS_VERSION}"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://localhost:8080
      - JENKINS_ADMIN_ID=builder
      - JENKINS_ADMIN_PASSWORD=builder
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - OMGSERVERS_BUILDER_USER_ID=builder
      - OMGSERVERS_BUILDER_USER_PASSWORD=builder
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5000
  service:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - database
      - broker
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${SERVICE_LOGGING_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database:5432/root
      - OMGSERVERS_BROKER_HOST=broker
      - OMGSERVERS_SERVER_URI=http://gateway:8080
      - OMGSERVERS_INITIALIZATION_SERVER_INDEX_SERVERS=http://gateway:8080
      - OMGSERVERS_BOOTSTRAP_ENABLED=TRUE
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__MAX_CONTAINERS=16
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  dispatcher:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - service
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${DISPATCHER_LOGGING_LEVEL}
      - OMGSERVERS_SERVICE_URI=http://service:8080
networks:
  omgservers:
    name: omgservers