ARG OMGSERVERS_VERSION
FROM omgservers/omgservers-proxy:${OMGSERVERS_VERSION}
COPY src/main/docker/service.yaml /etc/envoy/service.yaml
COPY src/main/docker/service1.yaml /etc/envoy/service1.yaml
COPY src/main/docker/service2.yaml /etc/envoy/service2.yaml
COPY src/main/docker/service3.yaml /etc/envoy/service3.yaml
