FROM omgservers/omgservers-proxy:1.0.0-SNAPSHOT
COPY src/main/docker/standalone1.yaml /etc/envoy/standalone1.yaml
COPY src/main/docker/standalone2.yaml /etc/envoy/standalone2.yaml
COPY src/main/docker/standalone3.yaml /etc/envoy/standalone3.yaml