version: '2'
services:
  omgservers-docker:
    image: "alpine/socat"
    container_name: "omgservers-docker"
    networks:
      - omgservers-frontend
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  omgservers-service:
    image: "omgservers/omgservers-service"
    container_name: "omgservers-service"
    ports:
      - "10001:8080"
    networks:
      - omgservers-frontend
      - omgservers-backend
    depends_on:
      - omgservers-db
      - omgservers-mq
    environment:
      - DOCKER_HOST=tcp://omgservers-docker:2375
      - OMGSERVERS_LOG_LEVEL=INFO
      - OMGSERVERS_DATASOURCE_URL=postgresql://omgservers-db:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=omgservers-mq
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=0
      - OMGSERVERS_EXTERNAL_URI=http://omgservers-service:8080
      - OMGSERVERS_INTERNAL_URI=http://omgservers-service:8080
      - OMGSERVERS_SERVICE_USERNAME=omgservers-service
      - OMGSERVERS_SERVICE_PASSWORD=omgservers-service
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_ADDRESSES=http://omgservers-service:8080
      - OMGSERVERS_SHARD_COUNT=1
      - OMGSERVERS_BOOTSTRAP_SERVICE=true
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_DOCKER_NETWORK=omgservers-backend
  omgservers-db:
    image: "postgres:16.1"
    container_name: "omgservers-db"
    networks:
      - omgservers-backend
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  omgservers-mq:
    image: "rmohr/activemq"
    container_name: "omgservers-mq"
    ports:
      - 18161:8161
    networks:
      - omgservers-backend
networks:
  omgservers-frontend:
    name: omgservers-frontend
  omgservers-backend:
    name: omgservers-backend