name: localtesting

services:
  docker:
    image: "omgservers/docker:${OMGSERVERS_VERSION}"
    container_name: "docker"
    networks:
      - omgservers
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: "omgservers/database:${OMGSERVERS_VERSION}"
    container_name: "database"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    networks:
      - omgservers
  queues:
    image: "omgservers/queues:${OMGSERVERS_VERSION}"
    container_name: "queues"
    environment:
      - ARTEMIS_USER=queues
      - ARTEMIS_PASSWORD=queues
    ports:
      - "5672:5672"
      - "8161:8161"
    networks:
      - omgservers
  registry:
    image: "omgservers/registry:${OMGSERVERS_VERSION}"
    container_name: "registry"
    ports:
      - "5000:5000"
    networks:
      - omgservers
  builder:
    image: "omgservers/builder:${OMGSERVERS_VERSION}"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://localhost:7070
      - JENKINS_ADMIN_ID=builder
      - JENKINS_ADMIN_PASSWORD=builder
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5000
networks:
  omgservers:
    name: omgservers