local omgserver = require("omgservers.omgserver")

function init()
	omgserver:init(function()
		local runtime_qualifier = omgserver:get_qualifier()
		print("[GAME] Server was initialized, qualifier=" .. runtime_qualifier)
	end)
end

function update(self, dt)
	omgserver:update(dt, function(command_qualifier, command_body)
		print("[GAME] Command was received, qualifier=" .. command_qualifier)
	end)
end