version: '2'
services:
  omgservers-service-1:
    image: "omgservers/omgservers-service"
    container_name: "omgservers-service-1"
    ports:
      - "10001:8080"
    networks:
      - omgservers-frontend
      - omgservers-backend-1
    depends_on:
      - omgservers-db-1
      - omgservers-mq-1
    environment:
      - OMGSERVERS_LOG_LEVEL=INFO
      - OMGSERVERS_DATASOURCE_URL=postgresql://omgservers-db-1:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=omgservers-mq-1
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=0
      - OMGSERVERS_SERVICE_URI=http://omgservers-service-1:8080
      - OMGSERVERS_SERVICE_USERNAME=omgservers-service-1
      - OMGSERVERS_SERVICE_PASSWORD=omgservers-service-1
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_DOCKER_NETWORK=omgservers-service-1
  omgservers-db-1:
    image: "postgres:16.1"
    container_name: "omgservers-db-1"
    networks:
      - omgservers-backend-1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  omgservers-mq-1:
    image: "rmohr/activemq"
    container_name: "omgservers-mq-1"
    networks:
      - omgservers-backend-1
  omgservers-service-2:
    image: "omgservers/omgservers-service"
    container_name: "omgservers-service-2"
    ports:
      - "10002:8080"
    networks:
      - omgservers-frontend
      - omgservers-backend-2
    depends_on:
      - omgservers-db-2
      - omgservers-mq-2
    environment:
      - OMGSERVERS_LOG_LEVEL=INFO
      - OMGSERVERS_DATASOURCE_URL=postgresql://omgservers-db-2:5432/root
      - OMGSERVERS_DATASOURCE_USERNAME=root
      - OMGSERVERS_DATASOURCE_PASSWORD=root
      - OMGSERVERS_AMQP_HOST=omgservers-mq-2
      - OMGSERVERS_AMQP_PORT=5672
      - OMGSERVERS_AMQP_USERNAME=admin
      - OMGSERVERS_AMQP_PASSWORD=admin
      - OMGSERVERS_DATACENTER_ID=0
      - OMGSERVERS_NODE_ID=1
      - OMGSERVERS_SERVICE_URI=http://omgservers-service-2:8080
      - OMGSERVERS_SERVICE_USERNAME=omgservers-service-2
      - OMGSERVERS_SERVICE_PASSWORD=omgservers-service-2
      - OMGSERVERS_ADMIN_USERNAME=admin
      - OMGSERVERS_ADMIN_PASSWORD_HASH=$$2a$$10$$gK.CQHaj3R/eilNFooNzZOkmiidAEKxKF67qoL6rUPI5.6f9U3Mwi
      - OMGSERVERS_SHARD_COUNT=3
      - OMGSERVERS_TOKEN_LIFETIME=3600
      - OMGSERVERS_DOCKER_NETWORK=omgservers-service-2
  omgservers-db-2:
    image: "postgres:16.1"
    container_name: "omgservers-db-2"
    networks:
      - omgservers-backend-2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  omgservers-mq-2:
    image: "rmohr/activemq"
    container_name: "omgservers-mq-2"
    networks:
      - omgservers-backend-2
networks:
  omgservers-frontend:
  omgservers-backend-1:
  omgservers-backend-2: