name: development

services:
  docker:
    image: "omgservers/docker:${OMGSERVERS_VERSION}"
    container_name: "docker"
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: "omgservers/database:${OMGSERVERS_VERSION}"
    container_name: "database"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
    volumes:
      - database:/var/lib/postgresql/data
  queues:
    image: "omgservers/queues:${OMGSERVERS_VERSION}"
    container_name: "queues"
    environment:
      - ARTEMIS_USER=queues
      - ARTEMIS_PASSWORD=queues
    ports:
      - "8161:8161"
    networks:
      - omgservers
    volumes:
      - queues:/var/lib/artemis-instance
  registry:
    image: "omgservers/registry:${OMGSERVERS_VERSION}"
    container_name: "registry"
    environment:
      - OMGSERVERS_ENVIRONMENT=development
      - OMGSERVERS_AUTH_URL=http://localhost:8080
      - OMGSERVERS_SERVICE_URL=http://service:8080
    volumes:
      - ./cert.pem:/root/certs/bundle/cert.pem
      - registry:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - omgservers
  builder:
    image: "omgservers/builder:1.0.0-SNAPSHOT"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://localhost:8080
      - JENKINS_ADMIN_ID=builder
      - JENKINS_ADMIN_PASSWORD=builder
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - OMGSERVERS_BUILDER_USER_ID=270042155391647744
      - OMGSERVERS_BUILDER_USER_PASSWORD=builder
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5000
    volumes:
      - builder:/var/jenkins_home
  service:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - omgservers
    depends_on:
      - database
      - queues
    environment:
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${OMGSERVERS_LOGGING_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database:5432/root
      - OMGSERVERS_QUEUES_HOST=queues
      - OMGSERVERS_INDEX_SERVER_URI=http://service:8080
      - OMGSERVERS_BOOTSTRAP_INDEX_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_INDEX_SERVERS=http://service:8080
      - OMGSERVERS_BOOTSTRAP_ROOT_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_ADMIN_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_SUPPORT_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_ROUTER_USER_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_REGISTRY_USER_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_BUILDER_USER_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_SERVICE_USER_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DOCKER_HOST_ENABLED=true
      - OMGSERVERS_WORKERS_SERVICE_URI=http://service:8080
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  ctl:
    image: "omgservers/ctl:${OMGSERVERS_VERSION}"
    container_name: "ctl"
    restart: unless-stopped
    depends_on:
      - service
    environment:
      - DELAY=16
      - EXTERNAL_URL=http://service:8080
      - INTERNAL_URL=http://service:8080
      - ADMIN_USER_ID=223221505901723648
      - ADMIN_PASSWORD=admin
      - SUPPORT_USER_ID=231928170708729857
      - SUPPORT_PASSWORD=support
      - BACKGROUND=true
    networks:
      - omgservers
    volumes:
      - ctl:/root/.omgserversctl
volumes:
  builder:
    name: builder
    driver: local
  registry:
    name: registry
    driver: local
  database:
    name: database
    driver: local
  queues:
    name: queues
    driver: local
  ctl:
    name: ctl
    driver: local
networks:
  omgservers:
    name: omgservers