name: integration

services:
  ingress:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "ingress"
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./ingress_config.yaml:/etc/envoy/ingress_config.yaml:ro
    command: "-c /etc/envoy/ingress_config.yaml"
  docker:
    image: "alpine/socat"
    container_name: "docker"
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
    ports:
      - "5000:5000"
    networks:
      - omgservers
    command: "/etc/docker/registry/registry_config.yaml"
  builder:
    image: "omgservers/builder:${OMGSERVERS_VERSION}"
    container_name: "builder"
    ports:
      - "7070:8080"
    networks:
      - omgservers
    environment:
      - JENKINS_URL=http://builder:8080
      - JENKINS_ADMIN_ID=builder
      - JENKINS_ADMIN_PASSWORD=builder
      - JENKINS_ADMIN_TOKEN=1167db115da39e5c7776c661e463fe7933
      - OMGSERVERS_BUILDER_USER_ID=builder
      - OMGSERVERS_BUILDER_USER_PASSWORD=builder
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_REGISTRY=localhost:5000
  # service1
  gateway1:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway1"
    networks:
      - omgservers
    volumes:
      - ./gateway1_config.yaml:/etc/envoy/gateway_config.yaml:ro
    command: "-c /etc/envoy/gateway_config.yaml"
  database1:
    image: "postgres:16.1"
    container_name: "database1"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  broker1:
    image: "omgservers/broker:${OMGSERVERS_VERSION}"
    container_name: "broker1"
    environment:
      - ARTEMIS_USER=broker
      - ARTEMIS_PASSWORD=broker
    networks:
      - omgservers
  service1:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service1"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - database1
      - broker1
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${SERVICE_LOGGING_LEVEL}
      - OMGSERVERS_LOGGING_ACCESS_LOGS_ENABLED=${SERVICE_ACCESS_LOGS_ENABLED}
      - OMGSERVERS_LOGGING_TRAFFIC_LOGS_LEVEL=${SERVICE_TRAFFIC_LOGS_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database1:5432/root
      - OMGSERVERS_BROKER_HOST=broker1
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_SERVER_DATACENTER_ID=0
      - OMGSERVERS_SERVER_INSTANCE_ID=0
      - OMGSERVERS_SERVER_URI=http://gateway1:8080
      - OMGSERVERS_INITIALIZATION_SERVER_INDEX_SERVERS=http://gateway1:8080,http://gateway2:8080,http://gateway3:8080
      - OMGSERVERS_BOOTSTRAP_ENABLED=TRUE
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_ENABLED=true
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_0__MAX_CONTAINERS=16
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_1__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_1__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_1__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_1__MAX_CONTAINERS=16
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_2__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_2__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_2__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_DOCKER_HOSTS_2__MAX_CONTAINERS=16
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  dispatcher1:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher1"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - service1
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${DISPATCHER_LOGGING_LEVEL}
      - OMGSERVERS_SERVICE_URI=http://service1:8080
  # service2
  gateway2:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway2"
    networks:
      - omgservers
    volumes:
      - ./gateway2_config.yaml:/etc/envoy/gateway_config.yaml:ro
    command: "-c /etc/envoy/gateway_config.yaml"
  database2:
    image: "postgres:16.1"
    container_name: "database2"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  broker2:
    image: "omgservers/broker:${OMGSERVERS_VERSION}"
    container_name: "broker2"
    environment:
      - ARTEMIS_USER=broker
      - ARTEMIS_PASSWORD=broker
    networks:
      - omgservers
  service2:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service2"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - database2
      - broker2
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${SERVICE_LOGGING_LEVEL}
      - OMGSERVERS_LOGGING_ACCESS_LOGS_ENABLED=${SERVICE_ACCESS_LOGS_ENABLED}
      - OMGSERVERS_LOGGING_TRAFFIC_LOGS_LEVEL=${SERVICE_TRAFFIC_LOGS_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database2:5432/root
      - OMGSERVERS_BROKER_HOST=broker2
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_SERVER_DATACENTER_ID=0
      - OMGSERVERS_SERVER_INSTANCE_ID=1
      - OMGSERVERS_SERVER_URI=http://gateway2:8080
      - OMGSERVERS_INITIALIZATION_SERVER_INDEX_SERVERS=http://gateway1:8080,http://gateway2:8080,http://gateway3:8080
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  dispatcher2:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher2"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - service2
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${DISPATCHER_LOGGING_LEVEL}
      - OMGSERVERS_SERVICE_URI=http://service2:8080
  # service3
  gateway3:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway3"
    networks:
      - omgservers
    volumes:
      - ./gateway3_config.yaml:/etc/envoy/gateway_config.yaml:ro
    command: "-c /etc/envoy/gateway_config.yaml"
  database3:
    image: "postgres:16.1"
    container_name: "database3"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - omgservers
  broker3:
    image: "omgservers/broker:${OMGSERVERS_VERSION}"
    container_name: "broker3"
    environment:
      - ARTEMIS_USER=broker
      - ARTEMIS_PASSWORD=broker
    networks:
      - omgservers
  service3:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service3"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - database3
      - broker3
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${SERVICE_LOGGING_LEVEL}
      - OMGSERVERS_LOGGING_ACCESS_LOGS_ENABLED=${SERVICE_ACCESS_LOGS_ENABLED}
      - OMGSERVERS_LOGGING_TRAFFIC_LOGS_LEVEL=${SERVICE_TRAFFIC_LOGS_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database3:5432/root
      - OMGSERVERS_BROKER_HOST=broker3
      - OMGSERVERS_INDEX_SHARD_COUNT=3
      - OMGSERVERS_SERVER_DATACENTER_ID=0
      - OMGSERVERS_SERVER_INSTANCE_ID=2
      - OMGSERVERS_SERVER_URI=http://gateway3:8080
      - OMGSERVERS_INITIALIZATION_SERVER_INDEX_SERVERS=http://gateway1:8080,http://gateway2:8080,http://gateway3:8080
      - OMGSERVERS_BUILDER_URI=http://builder:8080
  dispatcher3:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher3"
    restart: unless-stopped
    networks:
      - omgservers
    depends_on:
      - service3
    environment:
      - OMGSERVERS_OTEL_DISABLED=true
      - OMGSERVERS_LOGGING_APP_LOGS_LEVEL=${DISPATCHER_LOGGING_LEVEL}
      - OMGSERVERS_SERVICE_URI=http://service3:8080
networks:
  omgservers:
    name: omgservers
