name: integration

services:
  ingress:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "ingress"
    command: "-c /etc/envoy/ingress_config.yaml"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - omgservers
    volumes:
      - ./ingress_config.yaml:/etc/envoy/ingress_config.yaml:ro
  docker:
    image: "alpine/socat"
    container_name: "docker"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: "registry:2.8.3"
    container_name: "registry"
    command: "/etc/docker/registry/registry_config.yaml"
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - omgservers
    volumes:
      - ./registry_config.yaml:/etc/docker/registry/registry_config.yaml:ro
      - ./jwt_issuer_cert.pem:/root/certs/bundle/jwt_issuer_cert.pem
  cache:
    image: redis:7
    container_name: "cache"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - omgservers
  # shard1
  gateway1:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway1"
    command: "-c /etc/envoy/gateway_config.yaml"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - ./gateway1_config.yaml:/etc/envoy/gateway_config.yaml:ro
  database1:
    image: "postgres:16.1"
    container_name: "database1"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=omgservers
      - POSTGRES_PASSWORD=omgservers
      - POSTGRES_DB=omgservers
    networks:
      - omgservers
  service1:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service1"
    restart: unless-stopped
    depends_on:
      - database1
    networks:
      - omgservers
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database1:5432/omgservers
      - OMGSERVERS_DATABASE_PASSWORD=omgservers
      - OMGSERVERS_CACHE_HOSTS=redis://cache:6379
      - OMGSERVERS_USER_PASSWORD=service
      - OMGSERVERS_INDEX_SHARDS_0_=http://gateway1:8080
      - OMGSERVERS_INDEX_SHARDS_1_=http://gateway2:8080
      - OMGSERVERS_INDEX_SHARDS_2_=http://gateway3:8080
      - OMGSERVERS_SLOTS_COUNT=3
      - OMGSERVERS_MASTER_URI=http://gateway1:8080
      - OMGSERVERS_SHARD_ID=0
      - OMGSERVERS_SHARD_URI=http://gateway1:8080
      - OMGSERVERS_CLIENT_DISPATCHER_URI=ws://localhost:8080
      - OMGSERVERS_RUNTIME_SERVICE_URI=http://ingress:8080
      - OMGSERVERS_RUNTIME_DISPATCHER_URI=ws://dispatcher:8080
      - OMGSERVERS_REGISTRY_URI=http://localhost:5000
      - OMGSERVERS_ADMIN_USER_PASSWORD=admin
      - OMGSERVERS_SUPPORT_USER_PASSWORD=support
      - OMGSERVERS_SERVICE_USER_PASSWORD=service
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__SERVER_URI=http://localhost
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MAX_CONTAINERS=16
    volumes:
      - ./jwt_private_key.pem:/jwt_issuer/private_key.pem:ro
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
      - ./jwt_issuer_cert.pem:/jwt_issuer/cert.pem:ro
  # service2
  gateway2:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway2"
    command: "-c /etc/envoy/gateway_config.yaml"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - ./gateway2_config.yaml:/etc/envoy/gateway_config.yaml:ro
  database2:
    image: "postgres:16.1"
    container_name: "database2"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=omgservers
      - POSTGRES_PASSWORD=omgservers
      - POSTGRES_DB=omgservers
    networks:
      - omgservers
  service2:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service2"
    restart: unless-stopped
    depends_on:
      - database2
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database2:5432/omgservers
      - OMGSERVERS_DATABASE_PASSWORD=omgservers
      - OMGSERVERS_CACHE_HOSTS=redis://cache:6379
      - OMGSERVERS_USER_PASSWORD=service
      - OMGSERVERS_INDEX_SHARDS_0_=http://gateway1:8080
      - OMGSERVERS_INDEX_SHARDS_1_=http://gateway2:8080
      - OMGSERVERS_INDEX_SHARDS_2_=http://gateway3:8080
      - OMGSERVERS_SLOTS_COUNT=3
      - OMGSERVERS_MASTER_URI=http://gateway1:8080
      - OMGSERVERS_SHARD_ID=1
      - OMGSERVERS_SHARD_URI=http://gateway2:8080
      - OMGSERVERS_CLIENT_DISPATCHER_URI=ws://localhost:8080
      - OMGSERVERS_RUNTIME_SERVICE_URI=http://ingress:8080
      - OMGSERVERS_RUNTIME_DISPATCHER_URI=ws://dispatcher:8080
      - OMGSERVERS_REGISTRY_URI=http://localhost:5000
      - OMGSERVERS_ADMIN_USER_PASSWORD=admin
      - OMGSERVERS_SUPPORT_USER_PASSWORD=support
      - OMGSERVERS_SERVICE_USER_PASSWORD=service
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__SERVER_URI=http://localhost
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MAX_CONTAINERS=16
    networks:
      - omgservers
    volumes:
      - ./jwt_private_key.pem:/jwt_issuer/private_key.pem:ro
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
      - ./jwt_issuer_cert.pem:/jwt_issuer/cert.pem:ro
  # shard3
  gateway3:
    image: "envoyproxy/envoy:v1.28-latest"
    container_name: "gateway3"
    command: "-c /etc/envoy/gateway_config.yaml"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - ./gateway3_config.yaml:/etc/envoy/gateway_config.yaml:ro
  database3:
    image: "postgres:16.1"
    container_name: "database3"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=omgservers
      - POSTGRES_PASSWORD=omgservers
      - POSTGRES_DB=omgservers
    networks:
      - omgservers
  service3:
    image: "omgservers/service:${OMGSERVERS_VERSION}"
    container_name: "service3"
    restart: unless-stopped
    depends_on:
      - database3
    environment:
      - OMGSERVERS_APP_LOG_LEVEL=${SERVICE_LOG_LEVEL}
      - OMGSERVERS_DATABASE_URL=postgresql://database3:5432/omgservers
      - OMGSERVERS_DATABASE_PASSWORD=omgservers
      - OMGSERVERS_CACHE_HOSTS=redis://cache:6379
      - OMGSERVERS_USER_PASSWORD=service
      - OMGSERVERS_INDEX_SHARDS_0_=http://gateway1:8080
      - OMGSERVERS_INDEX_SHARDS_1_=http://gateway2:8080
      - OMGSERVERS_INDEX_SHARDS_2_=http://gateway3:8080
      - OMGSERVERS_SLOTS_COUNT=3
      - OMGSERVERS_MASTER_URI=http://gateway1:8080
      - OMGSERVERS_SHARD_ID=2
      - OMGSERVERS_SHARD_URI=http://gateway3:8080
      - OMGSERVERS_CLIENT_DISPATCHER_URI=ws://localhost:8080
      - OMGSERVERS_RUNTIME_SERVICE_URI=http://ingress:8080
      - OMGSERVERS_RUNTIME_DISPATCHER_URI=ws://dispatcher:8080
      - OMGSERVERS_REGISTRY_URI=http://localhost:5000
      - OMGSERVERS_ADMIN_USER_PASSWORD=admin
      - OMGSERVERS_SUPPORT_USER_PASSWORD=support
      - OMGSERVERS_SERVICE_USER_PASSWORD=service
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__SERVER_URI=http://localhost
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__DOCKER_DAEMON_URI=tcp://docker:2375
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__CPU_COUNT=800
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MEMORY_SIZE=8192
      - OMGSERVERS_BOOTSTRAP_DEFAULT_POOL_SERVERS_0__MAX_CONTAINERS=16
    networks:
      - omgservers
    volumes:
      - ./jwt_private_key.pem:/jwt_issuer/private_key.pem:ro
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
      - ./jwt_issuer_cert.pem:/jwt_issuer/cert.pem:ro
  # Dispatcher
  dispatcher:
    image: "omgservers/dispatcher:${OMGSERVERS_VERSION}"
    container_name: "dispatcher"
    restart: unless-stopped
    networks:
      - omgservers
    volumes:
      - ./jwt_public_key.pem:/jwt_issuer/public_key.pem:ro
networks:
  omgservers:
    name: omgservers
