name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./projectctl build testWithSonar
      - name: Start containers
        run: ./projectctl environment integration up && sleep 90
      - name: Init registry
        run: docker tag omgservers/luajit:1.0.0-SNAPSHOT localhost:5000/omgservers/luajit:1.0.0-SNAPSHOT && docker push localhost:5000/omgservers/luajit:1.0.0-SNAPSHOT
      - name: Run tests
        run: ./projectctl environment integration test
      - name: Log builder job
        if: always()
        run: curl -v -u admin:1167db115da39e5c7776c661e463fe7933 http://localhost:7070/job/luajit-worker-builder-v1/1/consoleText
      - name: Log containers
        if: always()
        run: ./projectctl environment integration logs
      - name: Stop containers
        if: always()
        run: ./projectctl environment down
      - name: Log into Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push images
        run: ./projectctl build pushImages
