name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=OMGSERVERS_omgservers
      - name: Start containers
        run: docker compose -f omgservers-environment/omgservers-integration/src/compose.yaml up -d && sleep 90
      - name: Check status
        run: docker compose -f omgservers-environment/omgservers-integration/src/compose.yaml ps
      - name: Init registry
        run: docker tag omgservers/omgservers-luajit:1.0.0-SNAPSHOT localhost:5050/omgservers/omgservers-luajit:1.0.0-SNAPSHOT && docker push localhost:5050/omgservers/omgservers-luajit:1.0.0-SNAPSHOT
      - name: Integration testing
        run: mvn -B -Dquarkus.test.profile=test -DskipITs=false -f omgservers-tester/pom.xml verify
      - name: Log builder job
        if: always()
        run: curl -v -u admin:1167db115da39e5c7776c661e463fe7933 http://localhost:7070/job/luajit-worker-builder-v1/1/consoleText
      - name: Log containers
        if: always()
        run: docker compose -f omgservers-environment/omgservers-integration/src/compose.yaml logs
      - name: Stop containers
        if: always()
        run: docker compose -f omgservers-environment/omgservers-integration/src/compose.yaml down --remove-orphans
      - name: Log into Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push omgservers-service
        run: docker push omgservers/omgservers-service:1.0.0-SNAPSHOT
      - name: Push omgservers-builder
        run: docker push omgservers/omgservers-builder:1.0.0-SNAPSHOT
      - name: Push omgservers-gateway
        run: docker push omgservers/omgservers-gateway:1.0.0-SNAPSHOT
      - name: Push omgservers-jwtkeys
        run: docker push omgservers/omgservers-jwtkeys:1.0.0-SNAPSHOT
      - name: Push omgservers-luajit
        run: docker push omgservers/omgservers-luajit:1.0.0-SNAPSHOT
