name: Build
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage -Dsonar.projectKey=OMGSERVERS_omgservers
      - name: Start containers
        run: docker-compose -f omgservers-tester/localEnv/cluster/docker-compose.yaml up -d && sleep 90
      - name: Check status
        run: docker-compose -f omgservers-tester/localEnv/cluster/docker-compose.yaml ps
      - name: Integration testing
        run: mvn -B -Dquarkus.test.profile=local -DskipITs=false -DdockerCompose.skip=false -f omgservers-tester/pom.xml verify
      - name: Stop containers
        if: always()
        run: docker-compose -f omgservers-tester/localEnv/cluster/docker-compose.yaml down
      - name: Log into Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push omgservers-service
        run: docker push omgservers/omgservers-service:1.0.0-SNAPSHOT
      - name: Push omgservers-worker
        run: docker push omgservers/omgservers-worker:1.0.0-SNAPSHOT
